imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    #trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    trusted_hosts:   ~
    session:
        save_path:   ~  # use default php.ini settings
    fragments:       ~
    translator:      ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
    #form:
    #    resources:
    #        - "AcmeBundle:Form:form_div_layout.html.twig"

#bc_bootstrap:
#    less_filter: less
#    assets_dir:  %kernel.root_dir%/../vendor/twitter/bootstrap
#    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
# use mopa instead of bc_bootstrap
mopa_bootstrap:
    form:  # Adds twig form theme  support
      render_optional_text: false
    #menu: ~  # enables twig helpers for menu

# Assertic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [MSPBundle]
    #java: /usr/bin/java
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules, /usr/bin/less]
            apply_to:   "\.less$"
#       lessphp:
#                    file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
#                    apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
#    assets:
#            bootstrap_css:
#                inputs:
#                    #- %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
#                    - %kernel.root_dir%/../vendor/jquery-ui-bootstrap/jquery-ui-bootstrap/less/style.less
#                filters:
#                    - less
#                    - cssrewrite
#                output: css/bootstrap.css
#            bootstrap_js:
#                inputs:
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-transition.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js
#                    - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js
#                output: js/bootstrap.js
#            jquery:
#                inputs:
#                    - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
#                output: js/jquery.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
            enumstat: MSP\MSPBundle\DBAL\EnumStatType
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
#        entity_managers:
#            default:
#                mappings:
#                    SonataMediaBundle:  ~
#                    ApplicationSonataMediaBundle: ~
#                    MSPBundle: ~
#                    FOSUserBundle: ~
#                    SonataUserBundle: ~




# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# FOS User Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MSP\MSPBundle\Entity\User
    group:
        group_class: MSP\MSPBundle\Entity\Group
    registration:
        form:
            type: msp_user_registration

# Sonata Block Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text: ~
        sonata.block.service.rss: ~
        sonata.formatter.block.formatter: ~

# Sonata Admin Configuration
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    title:    Admin Dashboard
    title_logo: /img/msplogo.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

         # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display two dashboard blocks
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_blog, User Management]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Settings]

            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

#        groups:
#             sonata_page:
#                label: Page
#                items: ~

# Sonata Doctrine ORM Configuration
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

#    templates:
#        form:
#            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
#        filter:
#            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
#        types:
#            list:
#                array:      SonataAdminBundle:CRUD:list_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:list_date.html.twig
#                time:       SonataAdminBundle:CRUD:list_time.html.twig
#                datetime:   SonataAdminBundle:CRUD:list_trans.html.twig
#                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
#                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
#                string:     SonataAdminBUndle:CRUD:base_list_field.html.twig
#                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
#                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
#                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
#                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
#                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
#
#            show:
#                array:      SonataAdminBundle:CRUD:show_array.html.twig
#                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
#                date:       SonataAdminBundle:CRUD:show_date.html.twig
#                time:       SonataAdminBundle:CRUD:show_time.html.twig
#                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
#                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
#                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
#                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
#                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
#                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
#                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig

genemu_form:
    autocomplete: ~

# Sonata Media Configuration
sonata_media:
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        profile:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 70}

        wall:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small:  { width: 100 , quality: 100}
                big:    { width: 500 , quality: 70}

        gallery:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 100}
                big:   { width: 500 , quality: 70}
                medium: { width: 300 , quality: 70}

        header:
            providers:
                - sonata.media.provider.image

            formats:
                big:   { width: 900 , quality: 70}

        news:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

# Sonata User Configuration
sonata_user:
    class:
        user: MSP\MSPBundle\Entity\User
        group: MSP\MSPBundle\Entity\Group
    admin:
        user:
          class: MSP\MSPBundle\Admin\UserAdmin
        group:
          class: MSP\MSPBundle\Admin\GroupAdmin

#simple_things_entity_audit:
#    audited_entities:
#      - MSPBundle\Entity\KeyMeasurableValue

# Stof Doctrine Extension Configuration
stof_doctrine_extensions:
   default_locale: en_US
   orm:
       default:
          timestampable: true
          sluggable: true

# Listener and Admin Services
services:
    mspbundle.listener.before_listener:
        class: MSP\MSPBundle\EventListener\BeforeControllerListener
        arguments: [ @security.context ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    sonata.news.admin.post:
        class: Application\Sonata\NewsBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group:"sonata_blog", label:"Posts",  label_catalogue:"%sonata.news.admin.post.translation_domain%"}
        arguments: [null, Application\Sonata\NewsBundle\Entity\Post, SonataAdminBundle:CRUD]
        calls:
            - [ addChild, [@sonata.news.admin.comment]]

# KNP Paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    #template:
        #pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_pagination.html.twig    # sliding pagination controls template
        #sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# SonataNewsBundle Configuration
sonata_news:
    title:        My Sport Page Blog
    link:         http://mysport-page.com
    description:  You are your best advocate. Take control of your future today.
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection
    permalink:
        date:     %%1$04d/%%2$2d/%%3$2d/%%4$s
    comment:
        notification:
            emails:   [soumaouche@endertech.com]
            from:     msp@msp.stage.endertech.net
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    class:
        post:       Application\Sonata\NewsBundle\Entity\Post
        comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Application\Sonata\MediaBundle\Entity\Media
        user:       MSP\MSPBundle\Entity\User

    admin:
        post:
            class:       Application\Sonata\NewsBundle\Admin\PostAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle
        comment:
            class:       Sonata\NewsBundle\Admin\CommentAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle
        tag:
            class:       Sonata\NewsBundle\Admin\TagAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle

# SonataFormatterBundle Configuration
sonata_formatter:
    formatters:
        # markdown:
        #     service: sonata.formatter.text.markdown
        #     extensions:
        #         - sonata.formatter.twig.control_flow
        #         - sonata.formatter.twig.gist
        #         - sonata.media.formatter.twig
        # text:
        #     service: sonata.formatter.text.text
        #     extensions:
        #         - sonata.formatter.twig.control_flow
        #         - sonata.formatter.twig.gist
        #         - sonata.media.formatter.twig
        # rawhtml:
        #     service: sonata.formatter.text.raw
        #     extensions:
        #         - sonata.formatter.twig.control_flow
        #         - sonata.formatter.twig.gist
        #         - sonata.media.formatter.twig
        # twig:
        #     service: sonata.formatter.text.twigengine
        #     extensions: [] # Twig formatter cannot have extensions
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'

# Ivory CK Editor Configuration
# ivory_ck_editor:
#     default_config: default
#     configs:
#         default:
#             filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
#             filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
#             # Display images by default when clicking the image dialog browse button
#             filebrowserImageBrowseRouteParameters:
#                 provider: sonata.media.provider.image
#             filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
#             filebrowserUploadRouteParameters:
#                 provider: sonata.media.provider.file
#             # Upload file as image when sending a file from the image dialog
#             filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
#             filebrowserImageUploadRouteParameters:
#                 provider: sonata.media.provider.image
#                 context: my-context # Optional, to upload in a custom context

ivory_ck_editor:
    default_config: default
    configs:
        default:

            filebrowserBrowseRoute: elfinder

fm_elfinder:
    editor: ckeditor
    connector:
        roots:
            uploads:
                path: uploads

